### ISSUE TITLE
Too Long

### ISSUE THREAD

**Issue by qingmui** [qingmui/Queens-University-Canada#1]
The handbook is too long.
require more work to split to different edition

**Comment by i2000s** [comment]
Hi @qingmui,

Are you still working on this handbook? How's everything going?

Cheers,
Xiaodong

**Comment by qingmui** [comment]
Sorry, I am not working any more. It is too busy.

________________________________

**Comment by qingmui** [comment]
Please note this project is discontinued, and all the info is ported to WeChat Public Account: queensgps
